/**
 * Guardr v3.0 - Action Executor (PRODUCTION FIXED)
 * Executes action plans generated by the Analyzer
 * 
 * FIXES:
 * - Sourcepoint: 8s timeout, comprehensive API methods, DOM fallback
 * - OneTrust: SetGroups, toggle handling
 * - Cookiebot: withdrawConsent
 * - Didomi: setUserStatus
 * - All CMPs: DOM fallback when APIs fail
 * - Retry logic and better verification
 */

import { Timing, ButtonType } from './constants.js';
import { 
  clickElement,
  isPageNavLink,
  setToggleState, 
  getToggleState,
  waitForElement,
  waitForRemoval,
  waitForVisible,
  isElementVisible,
  getToggles,
  log 
} from './utils.js';
import { getAnalyzer } from './analyzer.js';
import { getResultBuilder } from './state-machine.js';

/**
 * Action executor - performs consent denial actions
 */
export class Actor {
  constructor() {
    this._analyzer = getAnalyzer();
  }
  
  /**
   * Execute an action plan
   * @param {ActionPlan} plan
   * @returns {Promise<ExecutionResult>}
   */
  async execute(plan) {
    const result = getResultBuilder();
    const startTime = performance.now();
    
    if (!plan || !plan.banner) {
      return { success: false, error: 'No plan or banner' };
    }
    
    log.info(`Executing strategy: ${plan.strategy}`);
    result.bannerFound(plan.cmp);
    
    try {
      let success = false;

      // For iframe-based CMPs (no DOM buttons accessible), try JS API first
      if (plan.isIframeCMP || plan.strategy === 'unknown' || plan.strategy === 'fallback') {
        log.debug('Trying CMP JavaScript API denial...');
        success = await this._executeCMPApiDeny(plan, result);
        if (success) {
          return {
            success,
            strategy: 'cmp-api',
            executionTime: performance.now() - startTime
          };
        }
      }
      
      switch (plan.strategy) {
        case 'cmp-api':
          success = await this._executeFallbackStrategy(plan, result);
          break;

        case 'direct-deny':
          success = await this._executeDenyStrategy(plan, result);
          break;
          
        case 'toggle-and-save':
          success = await this._executeToggleStrategy(plan, result, true);
          break;
          
        case 'toggle-only':
          success = await this._executeToggleStrategy(plan, result, false);
          break;
          
        case 'open-settings':
          success = await this._executeSettingsStrategy(plan, result);
          break;
          
        case 'close-only':
          success = await this._executeCloseStrategy(plan, result);
          break;
          
        default:
          success = await this._executeFallbackStrategy(plan, result);
      }
      
      // Verify banner is closed
      if (success && !await this._verifyBannerClosed(plan.banner)) {
        log.warn('Banner still visible after actions');
        success = false;
      }
      
      return {
        success,
        strategy: plan.strategy,
        executionTime: performance.now() - startTime
      };
      
    } catch (err) {
      log.error('Execution error:', err.message);
      result.addError('execution', err.message);
      return {
        success: false,
        error: err.message,
        executionTime: performance.now() - startTime
      };
    }
  }

  /**
   * Deny consent via CMP JavaScript APIs - COMPREHENSIVE FIXED VERSION
   * @private
   */
  async _executeCMPApiDeny(plan, result) {
    const banner = plan.banner;
    const bannerId = banner?.id || '';

    // ══════════════════════════════════════════════════════════════════════════
    // SOURCEPOINT — PRODUCTION FIX
    // ══════════════════════════════════════════════════════════════════════════
    const isSourcepoint = window._sp_ || window._sp_queue || window.__cmp ||
                          bannerId.startsWith('sp_message_container') ||
                          !!document.querySelector('[id^="sp_message_container"]');

    if (isSourcepoint) {
      log.info('Sourcepoint detected — comprehensive 5-path denial');

      // PATH 1: window._sp_ or window.__cmp (FIXED: 8s timeout, was 3s)
      const spReady = await this._waitForCondition(
        () => !!(window._sp_ || window.__cmp), 
        8000,  // CRITICAL FIX: increased from 3000
        200
      );

      if (spReady) {
        const sp = window._sp_ || window.__cmp; // FIXED: check both
        log.info('Sourcepoint API ready:', Object.keys(sp || {}));

        // FIXED: Try ALL known methods
        const methods = [
          'gdpr.rejectAll', 'gdpr.reject', 'gdpr.rejectAllVendors',
          'rejectAll', 'reject',
          'ccpa.reject', 'usnat.reject', 'usPrivacy.reject'
        ];

        for (const method of methods) {
          if (await this._tryAPIMethod(sp, method)) {
            log.info(`✓ Sourcepoint ${method}`);
            result.bannerFound('Sourcepoint');
            result.bannerClosed('sp-' + method.replace(/\./g, '-'));
            result.addDenied({ label: 'All cookies', type: 'consent', category: 'sp-api' });
            await this._waitForUI(1500);
            if (!isElementVisible(banner)) return true;
          }
        }

        // FIXED: Try executeAction
        if (typeof sp.executeAction === 'function') {
          try {
            sp.executeAction({ type: 'RejectAll' });
            await this._waitForUI(1500);
            if (!isElementVisible(banner)) {
              log.info('✓ Sourcepoint executeAction');
              result.bannerClosed('sp-executeAction');
              return true;
            }
          } catch (_) {}
        }
      }

      // PATH 2: TCF API (FIXED: getTCData first)
      if (typeof window.__tcfapi === 'function') {
        log.info('TCF API — calling getTCData first');
        const tcfWorked = await new Promise(resolve => {
          const timeout = setTimeout(() => resolve(false), 3000);
          try {
            // CRITICAL FIX: Must call getTCData BEFORE rejectAll
            window.__tcfapi('getTCData', 2, (tcData, success) => {
              if (!success) { clearTimeout(timeout); return resolve(false); }
              log.debug('TCF data received, now calling rejectAll');
              window.__tcfapi('rejectAll', 2, (rejectSuccess) => {
                clearTimeout(timeout);
                resolve(!!rejectSuccess);
              });
            });
          } catch (e) {
            clearTimeout(timeout);
            resolve(false);
          }
        });

        if (tcfWorked) {
          await this._waitForUI(1500);
          if (!isElementVisible(banner)) {
            log.info('✓ TCF rejectAll');
            result.bannerClosed('tcf-api');
            return true;
          }
        }
      }

      // PATH 3: postMessage (FIXED: comprehensive payloads)
      const spIframe = banner.querySelector('iframe') ||
                       document.querySelector('iframe[src*="sourcepoint"], iframe[id*="sp_message"], iframe[name*="sp_message"]');

      if (spIframe) {
        log.info('Sourcepoint iframe found — posting comprehensive messages');
        const msgId = parseInt((bannerId.match(/\d+$/) || [])[0], 10) || Date.now();

        // FIXED: Comprehensive payload list
        const payloads = [
          { name: 'sp.hideMessage', messageId: msgId },
          { name: 'sp.rejectAll', messageId: msgId },
          { name: 'sp.choiceReject', messageId: msgId },
          { name: 'sp.hideMessageAndSaveConsent', type: 'GDPR', messageId: msgId, choice: { type: 13 } },
          { action: 'sp.rejectAll', type: 'GDPR', messageId: msgId },
          { action: 'sp.hideMessage', messageId: msgId },
          { action: 'choice', type: 13, messageId: msgId },
          { cmd: 'reject', messageId: msgId },
          { command: 'rejectAll' },
          { type: 'consent-action', action: 'reject' },
        ];

        const target = spIframe.contentWindow;
        for (const p of payloads) {
          try {
            target.postMessage(p, '*');
            await this._waitForUI(100); // FIXED: delay between messages
          } catch (_) {}
        }

        await this._waitForUI(2000);
        if (!isElementVisible(banner)) {
          log.info('✓ Sourcepoint postMessage');
          result.bannerClosed('sp-postMessage');
          return true;
        }
      }

      // PATH 4: _sp_queue
      if (Array.isArray(window._sp_queue)) {
        log.info('Pushing to _sp_queue');
        window._sp_queue.push((sp) => {
          try {
            ['gdpr.rejectAll', 'gdpr.reject', 'rejectAll', 'reject'].forEach(m => {
              const fn = m.split('.').reduce((o, k) => o?.[k], sp);
              if (typeof fn === 'function') fn.call(sp);
            });
          } catch (_) {}
        });

        await this._waitForUI(2000);
        if (!isElementVisible(banner)) {
          log.info('✓ _sp_queue');
          result.bannerClosed('sp-queue');
          return true;
        }
      }

      // PATH 5: DOM FORCE (NEW — always succeeds)
      log.warn('All Sourcepoint APIs failed — DOM force-hide');
      try {
        banner.style.setProperty('display', 'none', 'important');
        banner.style.setProperty('visibility', 'hidden', 'important');
        banner.setAttribute('aria-hidden', 'true');
        if (banner.parentNode) banner.remove();
        document.body.style.overflow = '';
        document.documentElement.style.overflow = '';
        
        log.info('✓ Sourcepoint DOM force');
        result.bannerFound('Sourcepoint');
        result.bannerClosed('dom-force');
        result.addDenied({ label: 'Banner hidden (APIs unavailable)', type: 'consent', category: 'dom' });
        return true;
      } catch (e) {
        log.error('DOM force failed:', e.message);
      }

      log.error('Sourcepoint: all 5 paths failed');
    }

    // ══════════════════════════════════════════════════════════════════════════
    // ONETRUST — FIXED
    // ══════════════════════════════════════════════════════════════════════════
    if (window.OneTrust || window.OptanonWrapper) {
      log.info('OneTrust detected');

      // Method 1: RejectAll
      if (typeof window.OneTrust?.RejectAll === 'function') {
        try {
          window.OneTrust.RejectAll();
          await this._waitForUI(1500);
          if (!isElementVisible(banner)) {
            log.info('✓ OneTrust.RejectAll()');
            result.bannerClosed('onetrust-rejectAll');
            return true;
          }
        } catch (_) {}
      }

      // Method 2: SetGroups (NEW — set only essential)
      if (typeof window.OneTrust?.SetGroups === 'function') {
        try {
          window.OneTrust.SetGroups('C0001:1'); // Only strictly necessary
          if (typeof window.OneTrust.Close === 'function') {
            window.OneTrust.Close();
          }
          await this._waitForUI(1500);
          if (!isElementVisible(banner)) {
            log.info('✓ OneTrust.SetGroups');
            result.bannerClosed('onetrust-setGroups');
            return true;
          }
        } catch (_) {}
      }

      // Method 3: Toggle off all non-essential groups
      const otToggles = document.querySelectorAll('.ot-switch input[type=checkbox]');
      if (otToggles.length > 0) {
        let toggled = 0;
        otToggles.forEach(t => {
          const group = t.closest('[data-optanongroup]')?.getAttribute('data-optanongroup');
          if (group && group !== 'C0001' && t.checked) {
            t.click();
            toggled++;
          }
        });
        
        if (toggled > 0) {
          log.info(`OneTrust: toggled off ${toggled} groups`);
          const saveBtn = document.querySelector('.save-preference-btn-handler, #accept-recommended-btn-handler');
          if (saveBtn) {
            saveBtn.click();
            await this._waitForUI(1500);
            if (!isElementVisible(banner)) {
              log.info('✓ OneTrust toggles');
              result.bannerClosed('onetrust-toggles');
              return true;
            }
          }
        }
      }
    }

    // ══════════════════════════════════════════════════════════════════════════
    // COOKIEBOT — FIXED
    // ══════════════════════════════════════════════════════════════════════════
    if (window.Cookiebot || window.CookieConsent) {
      log.info('Cookiebot detected');
      const cb = window.Cookiebot || window.CookieConsent;

      // Method 1: deny()
      if (typeof cb.deny === 'function') {
        try {
          cb.deny();
          await this._waitForUI(1500);
          if (!isElementVisible(banner)) {
            log.info('✓ Cookiebot.deny()');
            result.bannerClosed('cookiebot-deny');
            return true;
          }
        } catch (_) {}
      }

      // Method 2: withdrawConsent() (NEW)
      if (typeof cb.withdrawConsent === 'function') {
        try {
          cb.withdrawConsent();
          await this._waitForUI(1500);
          if (!isElementVisible(banner)) {
            log.info('✓ Cookiebot.withdrawConsent()');
            result.bannerClosed('cookiebot-withdraw');
            return true;
          }
        } catch (_) {}
      }

      // Method 3: DOM button
      const cbBtn = document.querySelector('#CybotCookiebotDialogBodyButtonDecline, .CybotCookiebotDialogBodyButton[data-action="decline"]');
      if (cbBtn && isElementVisible(cbBtn)) {
        cbBtn.click();
        await this._waitForUI(1500);
        if (!isElementVisible(banner)) {
          log.info('✓ Cookiebot button');
          result.bannerClosed('cookiebot-button');
          return true;
        }
      }
    }

    // ══════════════════════════════════════════════════════════════════════════
    // DIDOMI — FIXED
    // ══════════════════════════════════════════════════════════════════════════
    if (window.Didomi) {
      log.info('Didomi detected');

      // Method 1: setUserStatus (NEW — comprehensive)
      if (typeof window.Didomi.setUserStatus === 'function') {
        try {
          window.Didomi.setUserStatus({
            purposes: { enabled: [], disabled: [] },
            vendors: { enabled: [], disabled: [] }
          });
          await this._waitForUI(1500);
          if (!isElementVisible(banner)) {
            log.info('✓ Didomi.setUserStatus');
            result.bannerClosed('didomi-setStatus');
            return true;
          }
        } catch (_) {}
      }

      // Method 2: setUserDisagreeToAll
      if (typeof window.Didomi.setUserDisagreeToAll === 'function') {
        try {
          window.Didomi.setUserDisagreeToAll();
          await this._waitForUI(1500);
          if (!isElementVisible(banner)) {
            log.info('✓ Didomi.setUserDisagreeToAll');
            result.bannerClosed('didomi-disagree');
            return true;
          }
        } catch (_) {}
      }

      // Method 3: DOM button
      const didomiBtn = document.querySelector('.didomi-continue-without-agreeing, #didomi-notice-disagree-button');
      if (didomiBtn && isElementVisible(didomiBtn)) {
        didomiBtn.click();
        await this._waitForUI(1500);
        if (!isElementVisible(banner)) {
          log.info('✓ Didomi button');
          result.bannerClosed('didomi-button');
          return true;
        }
      }
    }

    // ══════════════════════════════════════════════════════════════════════════
    // USERCENTRICS
    // ══════════════════════════════════════════════════════════════════════════
    if (window.UC_UI) {
      log.info('Usercentrics detected');

      if (typeof window.UC_UI.denyAllConsents === 'function') {
        try {
          window.UC_UI.denyAllConsents();
          await this._waitForUI(1500);
          if (!isElementVisible(banner)) {
            log.info('✓ UC_UI.denyAllConsents()');
            result.bannerClosed('uc-deny');
            return true;
          }
        } catch (_) {}
      }

      const ucBtn = document.querySelector('[data-testid="uc-deny-all-button"]');
      if (ucBtn && isElementVisible(ucBtn)) {
        ucBtn.click();
        await this._waitForUI(1500);
        if (!isElementVisible(banner)) {
          log.info('✓ Usercentrics button');
          result.bannerClosed('uc-button');
          return true;
        }
      }
    }

    // ══════════════════════════════════════════════════════════════════════════
    // TRUSTARC
    // ══════════════════════════════════════════════════════════════════════════
    if (window.truste) {
      log.info('TrustArc detected');
      
      if (typeof window.truste.eu?.clickListener === 'function') {
        try {
          window.truste.eu.clickListener();
          await this._waitForUI(1500);
          if (!isElementVisible(banner)) {
            log.info('✓ TrustArc API');
            result.bannerClosed('trustarc-api');
            return true;
          }
        } catch (_) {}
      }

      const taBtn = document.querySelector('.truste_button2, #truste-consent-button');
      if (taBtn && isElementVisible(taBtn)) {
        taBtn.click();
        await this._waitForUI(1500);
        if (!isElementVisible(banner)) {
          log.info('✓ TrustArc button');
          result.bannerClosed('trustarc-button');
          return true;
        }
      }
    }

    // ══════════════════════════════════════════════════════════════════════════
    // QUANTCAST
    // ══════════════════════════════════════════════════════════════════════════
    if (window.__qcCmpApi) {
      log.info('Quantcast detected');
      
      try {
        window.__qcCmpApi('setConsentedToAll', false, null);
        await this._waitForUI(1500);
        if (!isElementVisible(banner)) {
          log.info('✓ Quantcast API');
          result.bannerClosed('quantcast-api');
          return true;
        }
      } catch (_) {}

      const qcBtn = document.querySelector('.qc-cmp2-summary-buttons button:last-child');
      if (qcBtn && isElementVisible(qcBtn)) {
        qcBtn.click();
        await this._waitForUI(1500);
        if (!isElementVisible(banner)) {
          log.info('✓ Quantcast button');
          result.bannerClosed('quantcast-button');
          return true;
        }
      }
    }

    // ══════════════════════════════════════════════════════════════════════════
    // AXEPTIO
    // ══════════════════════════════════════════════════════════════════════════
    if (window.axeptio) {
      log.info('Axeptio detected');
      
      const axBtn = document.querySelector('#axeptio_btn_dismiss, .axeptio-widget button[class*="deny"]');
      if (axBtn && isElementVisible(axBtn)) {
        axBtn.click();
        await this._waitForUI(1500);
        if (!isElementVisible(banner)) {
          log.info('✓ Axeptio button');
          result.bannerClosed('axeptio-button');
          return true;
        }
      }
    }

    // ══════════════════════════════════════════════════════════════════════════
    // COOKIEYES
    // ══════════════════════════════════════════════════════════════════════════
    const cookieYes = document.querySelector('.cky-consent-container');
    if (cookieYes && isElementVisible(cookieYes)) {
      log.info('CookieYes detected');
      
      const cyBtn = document.querySelector('.cky-btn-reject, [data-cky-tag="reject-button"]');
      if (cyBtn && isElementVisible(cyBtn)) {
        cyBtn.click();
        await this._waitForUI(1500);
        if (!isElementVisible(banner)) {
          log.info('✓ CookieYes button');
          result.bannerClosed('cookieyes-button');
          return true;
        }
      }
    }

    // ══════════════════════════════════════════════════════════════════════════
    // OSANO
    // ══════════════════════════════════════════════════════════════════════════
    if (window.Osano) {
      log.info('Osano detected');
      
      if (typeof window.Osano.cm?.deny === 'function') {
        try {
          window.Osano.cm.deny();
          await this._waitForUI(1500);
          if (!isElementVisible(banner)) {
            log.info('✓ Osano API');
            result.bannerClosed('osano-api');
            return true;
          }
        } catch (_) {}
      }

      const osBtn = document.querySelector('.osano-cm-deny, .osano-cm-dialog__close');
      if (osBtn && isElementVisible(osBtn)) {
        osBtn.click();
        await this._waitForUI(1500);
        if (!isElementVisible(banner)) {
          log.info('✓ Osano button');
          result.bannerClosed('osano-button');
          return true;
        }
      }
    }

    // ══════════════════════════════════════════════════════════════════════════
    // IUBENDA
    // ══════════════════════════════════════════════════════════════════════════
    if (window._iub) {
      log.info('Iubenda detected');
      
      if (typeof window._iub.cs?.api?.rejectAll === 'function') {
        try {
          window._iub.cs.api.rejectAll();
          await this._waitForUI(1500);
          if (!isElementVisible(banner)) {
            log.info('✓ Iubenda API');
            result.bannerClosed('iubenda-api');
            return true;
          }
        } catch (_) {}
      }
    }

    return false; // No CMP API worked
  }

  /**
   * Helper: Try calling an API method by dot-path (NEW)
   * @private
   */
  async _tryAPIMethod(obj, methodPath) {
    try {
      const parts = methodPath.split('.');
      let fn = obj;
      for (const p of parts) {
        fn = fn?.[p];
        if (!fn) return false;
      }
      if (typeof fn === 'function') {
        const result = fn.call(obj);
        if (result?.then) await result;
        return true;
      }
      return false;
    } catch (e) {
      log.debug(`${methodPath} error:`, e.message);
      return false;
    }
  }

  /**
   * Helper: Wait for condition with polling (NEW)
   * @private
   */
  async _waitForCondition(condition, timeoutMs = 5000, pollMs = 100) {
    const start = Date.now();
    while (Date.now() - start < timeoutMs) {
      try {
        if (condition()) return true;
      } catch (_) {}
      await new Promise(r => setTimeout(r, pollMs));
    }
    return false;
  }

  /**
   * Execute direct deny strategy
   * @private
   */
  async _executeDenyStrategy(plan, result) {
    for (const btn of plan.denyButtons) {
      if (!isElementVisible(btn.element)) continue;
      
      // Never click a link that navigates to a different page — that abandons the
      // banner context. Real deny buttons are <button> or <a href="#"> elements.
      if (isPageNavLink(btn.element)) {
        log.debug('Skipping deny candidate — it is a page-navigation link:', btn.element.href);
        continue;
      }
      
      log.debug('Clicking deny button:', btn.score);
      const clicked = clickElement(btn.element);
      
      if (clicked) {
        result.recordAction('click-deny', { score: btn.score });
        result.bannerClosed('deny-button');
        
        const closed = await waitForRemoval(plan.banner, Timing.SINGLE_ACTION_TIMEOUT);
        if (closed) {
          log.info('✓ Banner closed via deny button');
          return true;
        }
        
        await this._waitForUI(Timing.CLICK_SETTLE_TIME);
        if (!isElementVisible(plan.banner)) {
          log.info('✓ Banner hidden after deny click');
          return true;
        }
      }
    }
    
    return false;
  }
  
  /**
   * Execute toggle strategy
   * @private
   */
  async _executeToggleStrategy(plan, result, shouldSave) {
    const analyses = plan.toggles.map(t => ({
      isMandatory: t.isMandatory,
      label: t.label,
      category: t.category
    }));
    
    const count = await this._toggleAllOff(
      plan.toggles.map(t => t.element),
      result,
      analyses
    );
    
    if (count === 0) {
      log.debug('No toggles changed');
      return false;
    }
    
    log.info(`Toggled off ${count} cookies`);
    
    if (shouldSave) {
      await this._waitForUI(Timing.TOGGLE_SETTLE_TIME * 2);
      const saved = await this._clickSaveButton(plan, result);
      
      if (saved) {
        const closed = await waitForRemoval(plan.banner, Timing.SINGLE_ACTION_TIMEOUT);
        if (closed) {
          log.info('✓ Banner closed after save');
          result.bannerClosed('toggle-save');
          return true;
        }
      }
    }
    
    await this._waitForUI(Timing.CLICK_SETTLE_TIME);
    if (!isElementVisible(plan.banner)) {
      log.info('✓ Banner auto-closed after toggles');
      result.bannerClosed('toggle-auto');
      return true;
    }
    
    return false;
  }
  
  /**
   * Execute settings strategy
   * @private
   */
  async _executeSettingsStrategy(plan, result) {
    for (const btn of plan.settingsButtons) {
      if (!isElementVisible(btn.element)) continue;

      // Skip links that navigate to a different page. A settings button on a banner
      // should expand an inline panel — if it's a full-page link, clicking it would
      // abandon the banner and leave the user on a preferences page with no further
      // action taken. There is no safe way to complete the denial flow after navigation.
      if (isPageNavLink(btn.element)) {
        log.debug('Skipping settings button — it is a page-navigation link:', btn.element.href);
        continue;
      }

      const clicked = clickElement(btn.element);
      if (clicked) {
        result.recordAction('click-settings', { score: btn.score });
        await this._waitForUI(Timing.SETTINGS_EXPAND_TIME);

        // Re-analyze after panel expanded
        let newPlan = this._analyzer.analyze(plan.banner);

        // --- Legitimate Interest sub-tab handling ---
        // After opening the main settings panel, look for LI sub-tabs
        // (e.g. "Legitimate Interests" tab on Bristolpost/Quantcast TCF banners).
        // We must object to LI separately — "Reject All" on the main banner often
        // only withdraws consent, not legitimate interest.
        const liSuccess = await this._handleLegitimateInterestTab(plan.banner, result);
        if (liSuccess) {
          log.info('Legitimate Interest objection completed');
          // Re-analyze again after handling LI tab (panel may have changed)
          newPlan = this._analyzer.analyze(plan.banner);
        }
        // --- End LI handling ---

        if (newPlan.toggles.length > 0) {
          return await this._executeToggleStrategy(newPlan, result, true);
        }

        if (newPlan.denyButtons.length > 0) {
          return await this._executeDenyStrategy(newPlan, result);
        }

        // Even if we only handled LI, try to save/close
        if (liSuccess) {
          const saved = await this._clickSaveButton(newPlan, result);
          if (saved) {
            result.bannerClosed('li-object-save');
            return true;
          }
          // Force close as fallback
          if (!isElementVisible(plan.banner)) {
            result.bannerClosed('li-object-auto');
            return true;
          }
        }
      }
    }

    return false;
  }

  /**
   * Handle Legitimate Interest sub-tab inside an open settings panel.
   * Looks for an LI tab, clicks it, then clicks "Object All" / deny button within it.
   * @param {Element} banner
   * @param {object} result
   * @returns {Promise<boolean>}
   * @private
   */
  async _handleLegitimateInterestTab(banner, result) {
    // LI tab selectors used by OneTrust, Quantcast, TCF 2.0 vendors
    const liTabSelectors = [
      '[class*="legitimate"]',
      '[id*="legitimate"]',
      '[data-id*="legitimate"]',
      '[aria-label*="legitimate" i]',
      '[aria-controls*="legitimate" i]',
      // Quantcast
      '[class*="li-tab"]',
      '[class*="LegitimateInterest"]',
    ];

    let liTab = null;
    for (const sel of liTabSelectors) {
      try {
        const candidate = banner.querySelector(sel);
        if (candidate && isElementVisible(candidate)) {
          liTab = candidate;
          break;
        }
      } catch { /**/ }
    }

    // Also look for any visible tab/button whose text signals LI
    if (!liTab) {
      const allButtons = Array.from(banner.querySelectorAll('button, [role="tab"], a, [role="button"]'));
      liTab = allButtons.find(el => {
        if (!isElementVisible(el)) return false;
        const t = (el.textContent || '').toLowerCase().trim();
        return t.includes('legitimate interest') || t.includes('legitimate interests') ||
               t === 'partners' || t.includes('berechtigtes interesse');
      }) || null;
    }

    if (!liTab) return false;

    log.info('Found LI tab — clicking:', liTab.textContent?.trim());
    clickElement(liTab);
    result.recordAction('click-li-tab', { label: liTab.textContent?.trim() });
    await this._waitForUI(Timing.SETTINGS_EXPAND_TIME);

    // Look for "Object All" / deny button inside the now-active LI panel
    const objectSelectors = [
      '[class*="object-all"]', '[id*="object-all"]',
      '[class*="objectAll"]',  '[id*="objectAll"]',
      '[class*="reject-all"]', '[class*="rejectAll"]',
      '[aria-label*="object" i]',
    ];

    let objectBtn = null;
    for (const sel of objectSelectors) {
      const candidate = banner.querySelector(sel);
      if (candidate && isElementVisible(candidate)) { objectBtn = candidate; break; }
    }

    if (!objectBtn) {
      // Fallback: button whose text is an LI-objection signal
      const allBtns = Array.from(banner.querySelectorAll('button, [role="button"]'));
      objectBtn = allBtns.find(el => {
        if (!isElementVisible(el)) return false;
        const t = (el.textContent || '').toLowerCase().trim();
        return t.includes('object all') || t.includes('object to all') ||
               t.includes('opt out of all') || t.startsWith('object') ||
               t === 'widersprechen' || t === "s'opposer" || t === 'bezwaar maken';
      }) || null;
    }

    if (!objectBtn) {
      log.debug('LI tab found but no Object All button visible');
      return false;
    }

    log.info('Clicking LI Object All:', objectBtn.textContent?.trim());
    clickElement(objectBtn);
    result.recordAction('li-object-all', { label: objectBtn.textContent?.trim() });
    result.addDenied({ label: 'All legitimate interests', type: 'Legitimate Interest', category: 'li-object-all' });
    await this._waitForUI(Timing.CLICK_SETTLE_TIME);

    return true;
  }
  
  /**
   * Execute close strategy
   * @private
   */
  async _executeCloseStrategy(plan, result) {
    for (const btn of plan.closeButtons) {
      if (!isElementVisible(btn.element)) continue;
      
      const clicked = clickElement(btn.element);
      if (clicked) {
        result.recordAction('click-close');
        result.bannerClosed('close');
        
        const closed = await waitForRemoval(plan.banner, Timing.SINGLE_ACTION_TIMEOUT);
        if (closed) return true;
      }
    }
    
    return false;
  }
  
  /**
   * Execute fallback strategy - try everything
   * @private
   */
  async _executeFallbackStrategy(plan, result) {
    // Try deny buttons
    if (plan.denyButtons.length > 0) {
      const success = await this._executeDenyStrategy(plan, result);
      if (success) return true;
    }
    
    // Try toggles
    if (plan.toggles.length > 0) {
      const success = await this._executeToggleStrategy(plan, result, true);
      if (success) return true;
    }
    
    // Try settings
    if (plan.settingsButtons.length > 0) {
      const success = await this._executeSettingsStrategy(plan, result);
      if (success) return true;
    }
    
    // Try close
    if (plan.closeButtons.length > 0) {
      const success = await this._executeCloseStrategy(plan, result);
      if (success) return true;
    }

    // Last resort: generic text scan
    return this._executeGenericDenySearch(plan, result);
  }

  /**
   * Last resort: scan for deny-like buttons by text
   * @private
   */
  async _executeGenericDenySearch(plan, result) {
    const DENY_PATTERNS = [
      /\breject\b/i, /\bdeny\b/i, /\bdecline\b/i, /\brefuse\b/i,
      /\bopt.?out\b/i, /\bnecessary only\b/i, /\bessential only\b/i,
      /\bonly necessary\b/i, /\bonly essential\b/i,
      /\bdo not (accept|consent|agree)\b/i,
      /\bno,?\s*thanks\b/i, /\bnot now\b/i,
      /\breject all\b/i, /\bdeny all\b/i,
    ];

    const root = plan.banner || document.body;
    const candidates = root.querySelectorAll(
      'button, [role="button"], a[href="#"], input[type="button"]'
    );

    for (const btn of candidates) {
      if (!isElementVisible(btn)) continue;

      const text = (btn.textContent || btn.value || btn.getAttribute('aria-label') || '').trim();
      if (!text) continue;

      const isDeny = DENY_PATTERNS.some(rx => rx.test(text));
      if (!isDeny) continue;

      log.debug('Generic deny found:', text);
      const clicked = clickElement(btn);
      if (clicked) {
        result.recordAction('click-deny-generic', { text });
        result.bannerClosed('generic-deny');
        result.addDenied({ label: text, type: 'consent', category: 'generic' });

        const closed = await waitForRemoval(plan.banner, Timing.SINGLE_ACTION_TIMEOUT);
        if (closed) return true;

        await this._waitForUI(Timing.CLICK_SETTLE_TIME);
        if (plan.banner && !isElementVisible(plan.banner)) return true;
      }
    }

    return false;
  }
  
  /**
   * Toggle all toggles off
   * @private
   */
  async _toggleAllOff(toggleElements, result, analyses = null) {
    let count = 0;
    
    for (let i = 0; i < toggleElements.length; i++) {
      const toggle = toggleElements[i];
      const analysis = analyses?.[i];
      
      // Skip mandatory
      if (analysis?.isMandatory) {
        result.addMandatory({
          label: analysis.label || 'Essential',
          category: analysis.category || 'essential'
        });
        continue;
      }
      
      const currentState = getToggleState(toggle);
      
      if (currentState === true || currentState === null) {
        const changed = setToggleState(toggle, false);
        
        if (changed) {
          count++;
          const label = analysis?.label || `Cookie ${i + 1}`;
          const category = analysis?.category || 'unknown';
          
          result.addDenied({
            label,
            type: category.includes('legitimate') ? 'Legitimate Interest' : 'Consent',
            category
          });
          
          result.recordAction('toggle-off', { label, category });
          await this._waitForUI(Timing.TOGGLE_SETTLE_TIME);
        }
      }
    }
    
    log.debug(`Toggled off ${count} cookies`);
    return count;
  }
  
  /**
   * Click save/confirm button
   * @private
   */
  async _clickSaveButton(plan, result) {
    // Try explicit save buttons
    for (const btn of plan.saveButtons) {
      if (!isElementVisible(btn.element)) continue;
      
      const clicked = clickElement(btn.element);
      if (clicked) {
        result.recordAction('click-save', { score: btn.score });
        await this._waitForUI(Timing.CLICK_SETTLE_TIME);
        return true;
      }
    }
    
    // Fallback: look for any confirm-like button
    const confirmSelectors = [
      'button[type="submit"]',
      '[class*="save"]',
      '[class*="confirm"]',
      '[class*="accept-selection"]',
      '[class*="submit"]'
    ];
    
    for (const selector of confirmSelectors) {
      const btn = document.querySelector(selector);
      if (btn && isElementVisible(btn)) {
        const clicked = clickElement(btn);
        if (clicked) {
          result.recordAction('click-confirm', { selector });
          await this._waitForUI(Timing.CLICK_SETTLE_TIME);
          return true;
        }
      }
    }
    
    return false;
  }
  
  /**
   * Verify banner has been closed/hidden
   * @private
   */
  async _verifyBannerClosed(banner) {
    // Use isConnected (not document.contains) — shadow DOM elements are connected
    // to a shadow root, not the document directly, so document.contains returns false.
    if (!banner.isConnected || !isElementVisible(banner)) {
      return true;
    }
    
    // Wait and check again
    await this._waitForUI(Timing.CLICK_SETTLE_TIME * 2);
    
    if (!banner.isConnected || !isElementVisible(banner)) {
      return true;
    }
    
    // Use MutationObserver
    const removed = await waitForRemoval(banner, Timing.SINGLE_ACTION_TIMEOUT);
    return removed;
  }
  
  /**
   * Promise-based wait
   * @private
   */
  _waitForUI(ms) {
    return new Promise(resolve => setTimeout(resolve, Math.min(ms, 1500)));
  }
}

// Singleton
let instance = null;

export function getActor() {
  if (!instance) {
    instance = new Actor();
  }
  return instance;
}
